### ISSUE TITLE
安裝好之後的問題

### ISSUE THREAD

**Issue by XasonLai** [Ping-Lin/PikaBall_Connect#1]
不好意思，我安裝好python 跟 pygame的套件後，還是無法順利去玩。。是為何？？

**Comment by Ping-Lin** [comment]
請問是有出現什麼錯誤訊息嗎?
可能要麻煩你提供一下pygame version比較能夠推測發生的問題，謝謝！

**Comment by XasonLai** [comment]
Pygame (1.9.2b6)               - Python Game Development

我是點第一個 1v1進去之後 就黑色畫面，然後跳出來。
抱歉我程式很弱弱的，可能回答的有限，這是我跑出來的訊息，我直接全部貼給你

2016-07-22 17:24:57.227 Python[34460:1118783] 17:24:57.227 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Traceback (most recent call last):
  File "menu.py", line 98, in <module>
    main()
  File "menu.py", line 95, in main
    runGame(buttonGroup, txtImgs, txtbox)
  File "menu.py", line 30, in runGame
    buttonGroup[0].update(clickPos, page)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygame/sprite.py", line 462, in update
    s.update(*args)
  File "/Users/jason/Downloads/PikaBall_Connect-master/menuButton.py", line 38, in update
    mainScreen.main()
  File "/Users/jason/Downloads/PikaBall_Connect-master/mainScreen.py", line 162, in main
    musicButton = button.Button(pygame.Rect(gbv.WINWIDTH-200, 20, 60, 60), 1)
  File "/Users/jason/Downloads/PikaBall_Connect-master/button.py", line 22, in **init**
    self.images.append(loadImg("musicOn.png", rect.w, rect.h))
  File "/Users/jason/Downloads/PikaBall_Connect-master/button.py", line 63, in loadImg
    image = pygame.image.load(path).convert_alpha()
pygame.error: Failed loading libpng.dylib: dlopen(libpng.dylib, 2): image not found

**Comment by Ping-Lin** [comment]
目前看起來是有兩個問題
1. pygame已經很久沒更新的樣子， 所以他的lib可能有不支援的情形
2. 不過會當掉的主因應該是最後一行
pygame.error: Failed loading libpng.dylib: dlopen(libpng.dylib, 2): image not found
你可以試試看stacjoverflow的解法試試看。
http://stackoverflow.com/questions/22790792/libpng-not-linked-on-mac-osx-10-9-2

**Comment by XasonLai** [comment]
最後一行是因為找不到這個 lib的關係嗎？？？
我等等試試看！！！
謝謝你！！！

**Comment by XasonLai** [comment]
我試了 stackoverflow那個方法，但是出現新的問題：
2016-07-25 11:01:08.213 Python[37717:1280122] 11:01:08.213 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
libpng warning: iCCP: known incorrect sRGB profile
Segmentation fault: 11

碰到這個新的問題，是我Python版本的問題嗎？？

**Comment by Ping-Lin** [comment]
我剛試了在ubuntu安裝
以下是主要步驟：
1. 下載檔案
git clone https://github.com/Ping-Lin/PikaBall_Connect
2. 安裝 pip
sudo apt-get install python-pip
3. upgrade pip
sudo pip install --upgrade pip
4. 安裝pygame套件 (他安裝的是pygame 1.9.2.dev1)
sudo apt-get install pygame
5. 切換到當下資料夾後，執行遊戲
python menu.py

依照此步驟是可以正常開啟的
可以麻煩你試試看如果是安裝pygame 1.9.2.dev1是否可正常執行? 謝謝！

如果還不行的話，就我的理解上是lib的問題，這個我也不太知道怎麼處理 (汗
目前有測試的環境是MAC OS 10.10、10.11.5 以及 Ubuntu 4.9.2-10ubuntu13，這些系統都可以正常執行
所以可能必須要查看看你出現的warning 和 segmentation fault要怎麼處理掉

**Comment by XasonLai** [comment]
版主：
我這樣子指定安裝有錯誤嗎？？？
pip install "pygame==1.9.2.dev1"
No matching distribution found for pygame==1.9.2.dev1

還是我該怎麼做輸入？？？
（我電腦是用MAC 10.11.6）

**Comment by Ping-Lin** [comment]
不好意思
查詢後，你的pygame版本應是mac可以下載到最新的了
所以我索性也將版本升級到10.11.6 XD
不過嘗試後雖有warning但還是可以正常執行 (基本上warning還是可以正常執行)

以下提供一種解法你可以試試
重新安裝python
1. 安裝brew，如果你有安裝的話可以跳過這一個步驟 (這是brew官網(http://brew.sh)的安裝方式)
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
2. 重新安裝python
brew uninstall python
brew install python
3. 安裝pip
sudo easy_install pip
4. 升級pip到最新版
sudo pip install --upgrade pip
5. 重安裝pygame
sudo pip install --ignore-installed pygame

然後再跑一次程式看看

不好意思，因為我沒有將其包好，讓你花費這麼多時間
最近有空會開始修bug了！

**Comment by XasonLai** [comment]
不會拉，我也是想學習跟玩遊戲而已。
雖然我也有寫程式，但我還是很新手等級。

**Comment by Ping-Lin** [comment]
一起加油！在麻煩你回報了

**Comment by XasonLai** [comment]
我回來了，
我是不是安裝後，ＭＡＣ都會自己安裝這個版本pygame-1.9.2b6
我在 PikaBall_Connect 下面執行，python menu.py 。
得到以下的結果：
laizhizhongde-MacBook-Pro:PikaBall_Connect jason$ python menu.py 
2016-08-04 11:30:38.118 Python[47637:2024281] 11:30:38.118 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
libpng warning: iCCP: known incorrect sRGB profile
Segmentation fault: 11

**Comment by Ping-Lin** [comment]
那如果直接下
python mainScreen.py
試試看呢？
